# Generated by Django 4.1.5 on 2023-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
