# Generated by Django 4.1.5 on 2023-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('comment', models.TextField(blank=True)),
                ('star', models.IntegerField(blank=True)),
            ],
        ),
    ]
