# Generated by Django 4.1.5 on 2023-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_subcategory_product_subcategory_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('email', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('star', models.IntegerField(blank=True)),
                ('slug', models.CharField(max_length=500)),
            ],
        ),
    ]
